# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishes', to='login_app.User'),
        ),
    ]
